##
## Makefile
## Pi-Nex Sterownik C.O dla Raspberry Pi 0 1.1
##   Działa dzięki Mongoose - Embedded Web Server / Embedded Networking Library
## - https://cesanta.com/
##

DEBUG = -O3
CC = gcc
INCLUDE = -I./mongoose -I../MEMINFO -I../CPUUSAGE -I../DS3231 -I/usr/include -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads
CFLAGS = $(DEBUG) -Wall $(INCLUDE) -g 
LDFLAGS = -L/usr/lib -L/opt/vc/lib
LDLIBS = -lssl -lcrypto -ldl -lsndio -lbcm_host -lvchostif -lvcos -lvchiq_arm -pthread -lrt 
CFLAGS += -DMG_ENABLE_SSL 
LDLIBS += -lconfuse

LDLIB_EXTRA = -lwiringPi -lwiringPiDev
DS3231 = ../DS3231/DS3231.c ../DS3231/i2c.c
CPUUSAGE = ../CPUUSAGE/cpu_usage.c
MEMINFO = ../MEMINFO/mem_info.c
MONGOOSE = ./mongoose/mongoose.c

COMPONENTS = $(DS3231) $(CPUUSAGE) $(MEMINFO) $(MONGOOSE)

SRC =   pi-nex-web.c

OBJ = $(SRC:.c=.o)

BINS = $(SRC:.c=)

all: $(BINS)

clean:
	@echo "Cleaning directory..."
	$(RM) $(BINS)

pi-nex-web: pi-nex-web.c $(COMPONENTS)
	@echo [Building $@]
	@$(CC) $(CFLAGS) -o $@ pi-nex-web.c $(COMPONENTS) $(LDFLAGS) $(LDLIBS) $(LDLIB_EXTRA) -lm -I ..
